name: learn-env
channels:
  - defaults
dependencies:
  - appnope=0.1.0
  - asn1crypto=0.24.0
  - backcall=0.1.0
  - blas=1.0
  - ca-certificates=2018.03.07
  - certifi=2018.8.13
  - cffi=1.11.5
  - chardet=3.0.4
  - cryptography=2.3
  - cryptography-vectors=2.3
  - cython=0.28.5
  - decorator=4.3.0
  - idna=2.7
  - intel-openmp=2018.0.3
  - ipython=6.5.0
  - ipython_genutils=0.2.0
  - jedi=0.12.1
  - jsonschema=2.6.0
  - jupyter_core=4.4.0
  - libcxx=4.0.1
  - libcxxabi=4.0.1
  - libedit=3.1.20170329
  - libffi=3.2.1
  - libgfortran=3.0.1
  - matplotlib=3.0.2
  - mkl
  - mkl_fft
  - mkl_random
  - nb_conda
  - nbformat=4.4.0
  - ncurses=6.1
  - numpy
  - numpy-base
  - openssl=1.0.2p
  - pandas=0.23.4
  - parso=0.3.1
  - pexpect=4.6.0
  - pickleshare=0.7.4
  - pip=10.0.1
  - plotly=3.1.0
  - prompt_toolkit=1.0.15
  - ptyprocess=0.6.0
  - pycparser=2.18
  - pygments=2.2.0
  - pyopenssl=18.0.0
  - pysocks=1.6.8
  - python=3.6.6
  - python-dateutil
  - pytz=2018.5
  - readline=7.0
  - requests=2.19.1
  - retrying=1.3.3
  - scikit-learn=0.20.2
  - scipy=1.1.0
  - seaborn=0.9.0
  - setuptools=40.0.0
  - simplegeneric=0.8.1
  - six=1.11.0
  - sqlite=3.24.0
  - tk=8.6.7
  - traitlets=4.3.2
  - urllib3=1.23
  - wcwidth=0.1.7
  - wheel=0.31.1
  - xlrd=1.1.0
  - xz=5.2.4
  - zlib=1.2.11
  - py-xgboost=0.72
  - tqdm
  - statsmodels=0.9.0
  - beautifulsoup4=4.7.1
  - networkx=2.2
  - nltk=3.4
  - gensim=3.4.0
  - h5py=2.9.0
  - pyspark=2.4.0
  - patsy=0.5.1
  - pydotplus=2.0.2
  - pip:
    - ipynb==0.5.1
    - pytest==3.7
    - tensorflow==1.6
    - keras==2.2.1
    - obscure==1.0.1
    - folium
    - imbalanced-learn
    - graphviz
prefix: /anaconda3/envs/learn-env
